if (WIN32)
   if (DEFINED ENV{LOCALAPPDATA})
      file(TO_CMAKE_PATH $ENV{LOCALAPPDATA}/registry REGISTRY_ARCHIVE)
   elseif (DEFINED ENV{APPDATA})
      file(TO_CMAKE_PATH $ENV{APPDATA}/registry REGISTRY_ARCHIVE)
   else ()
      message(FATAL_ERROR "Could not determine vcpkg binary cache path")
   endif ()
else ()
   if (DEFINED ENV{XDG_CACHE_HOME})
      set(REGISTRY_ARCHIVE $ENV{XDG_CACHE_HOME}/registry)
   elseif (DEFINED ENV{HOME})
      set(REGISTRY_ARCHIVE $ENV{HOME}/.cache/registry)
   else ()
      message(FATAL_ERROR "Could not determine vcpkg binary cache path")
   endif ()
endif ()

set(LLVM_ROOT ${REGISTRY_ARCHIVE}/LLVM)