set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

cmake_host_system_information(RESULT HOST_SYSTEM_PROCESSOR QUERY OS_PLATFORM)
string(TOLOWER ${HOST_SYSTEM_PROCESSOR} HOST_SYSTEM_PROCESSOR)

if (HOST_SYSTEM_PROCESSOR MATCHES "^(amd64|x86_64)$")
   set(VCPKG_TARGET_ARCHITECTURE x64)
elseif (HOST_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
   set(VCPKG_TARGET_ARCHITECTURE arm64)
else ()
   message(FATAL_ERROR "Unsupported host architecture: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
endif ()

if (CMAKE_HOST_WIN32)
   set(VCPKG_LOAD_VCVARS_ENV ON)
endif ()

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/clang.cmake)